version: 2.1

orbs:
  jira: circleci/jira@1.3.1

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - jira/notify:
          job_type: deployment

workflows:
  my-workflow:
    when:
      equal: [api, << pipeline.trigger_source >>]
    jobs:
      - my-job
 
