version: 2.1

orbs:
  jira: circleci/jira@1.3.1

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    shell: /bin/bash -euxo pipefail
    steps:
      - jira/notify:
          job_type: deployment

workflows:
  my-workflow:
    jobs:
      - my-job
 
