version: 2.1

orbs:
  jira: circleci/jira@1.3.1



parameters:
  jira_keys:
    default: ""
    description: The key for jira that needs to be set.
    type: string

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - jira/notify:
          job_type: deployment
          jira_keys: << pipeline.parameters.jira_keys >>

workflows:
  my-workflow:
    when:
      equal: [api, << pipeline.trigger_source >>]
    jobs:
      - my-job
 
